version: '3.8'
services:
  uv-front:
    image: liderbackend/uv_front:4.0.1
    env_file:
      - .env_universum_si
    ports:
      - "3003:3003"
  uv-sync:
    image: liderbackend/uv_sync:1.0.0
    env_file:
      - .env_universum_sync
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "3002:3002"
    networks:
      - uv-network
  uv-backend:
    image: liderbackend/uv_backend:2.0.0
    env_file:
      - .env_api_backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "3001:3001"
    networks:
      - uv-network
  minio:
    image: minio/minio:latest
    container_name: uv_minio
    environment:
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=13245Az!
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
    networks:
      - uv-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  uv-network:
    driver: bridge

volumes:
  minio_data:
    driver: local
