version: '3.8'
services:
  uv-front:
    image: talentumfront/uv_front:2.0.2
    restart: always
    env_file:
      - .env_si
    ports:
      - "3003:3003"
  uv-backend:
    image: talentumfront/uv_backend:2.0.2
    restart: always
    env_file:
      - .env_api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "3001:3001"
    networks:
      - uv-network
  minio:
    image: minio/minio:latest
    container_name: uv_minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=12345Az!
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
    networks:
      - uv-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  uv-network:
    driver: bridge

volumes:
  minio_data:
    driver: local
